core/urls.py
from unicodedata import name
from django.urls import path, include


from .views import  CheckoutView, ItemDetailView, ItemList, add_coupon,add_to_cart, OrderSummaryView, remove_from_cart,remove_single_item_from_cart
from django.shortcuts import render
app_name = "core"
urlpatterns = [
    path('',ItemList.as_view(),name='item-list'),
#    path('checkout/',lambda request: render(request,'checkout-page.html'),name='checkout'),
    path('product/add-to-cart/<slug>/', add_to_cart,name='add-to-cart'),
    path('product/remove-from-cart/<slug>/', remove_from_cart,name='remove-from-cart'),
    path('product/<slug>/', ItemDetailView.as_view(),name='item-detail'),
    path('order-summary/', OrderSummaryView.as_view(),name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
     name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('add-coupon/',add_coupon , name="add-coupon")

]
"""     path('payment/',CreatePayment.as_view(), name="payment"),
    path('payment-confirm/',PaymentConfirmation.as_view(), name="payment-confirmation"),
    path("payment-status/<int:pk>/",PaymentStatus.as_view(),name="payment-status"), """

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls',namespace='core')),
    path('supervisor/',include('supervisor.urls',namespace='supervisor')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

supervisor/urls.py
from django.urls import path, include

from supervisor.views import CreateSupervisorView, ItemList, add_category, CreateItemView, dashboard, get_email,CategoryListView

app_name='supervisor'

urlpatterns = [
    path('',dashboard,name='dashboard'),
    path('add-supervisor/',CreateSupervisorView.as_view(),name='add-supervisor'),
    path('add-category/',add_category,name='add-category'),
    path('get-email/',get_email,name='get-email'),
    path('tables/',ItemList.as_view(),name='tables'),
    path('add-item/',CreateItemView.as_view(),name='add-item'),
    path('tables/categories/',CategoryListView.as_view(),name='categories'),
]

supervisor/models.py
from django.db import models

# Create your models here.

supervisor/forms.py
from django import forms
from core.constants import SUPERVISOR_TYPE,LABEL_CHOICES
from core.models import Category
from django.core.files.storage import FileSystemStorage

class SupervisorForm(forms.Form):
    email = forms.EmailField(max_length=70, widget=forms.EmailInput(attrs={
        "placeholder":"Email must be for an existing account",
        "class":"form-control"
    }))
    supervisor_type = forms.ChoiceField(widget=forms.RadioSelect(), choices=SUPERVISOR_TYPE)

class CategoryForm(forms.Form):
    category_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        "class":"form-control",
        "placeholder":"Category name (Jeans,Chemise ...)"
    }))

class ItemForm(forms.Form):
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        "class":"form-control",
        "placeholder":"Item title"
    }))
    label = forms.ChoiceField(widget=forms.RadioSelect(attrs={
        "class":"form-check-input",
        "type":"radio"
    }), choices=LABEL_CHOICES)
    price = forms.DecimalField(widget=forms.NumberInput(attrs={
        "class":"form-control",
        "placeholder":"Item price"
    }))
    discount_price = forms.DecimalField(widget=forms.NumberInput(attrs={
        "class":"form-control",
        "placeholder":"Item discount, default is 0"
    }))
    category = forms.ModelChoiceField(queryset = Category.objects.all(), widget=forms.Select(attrs={
        "class":"form-control"
    }))
    description = forms.CharField(widget=forms.Textarea(attrs={
        "class":"form-control",
        "id":"exampleFormControlTextarea1",
        "rows":"3",
        "placeholder":"Item available sizes, colors and other infos"
    }))
    quantity = forms.CharField(widget=forms.NumberInput(attrs={
        "class":"form-control",
        "placeholder":"Item quantity, if you dont want to specify quantity leave it blank"
    }))

supervisor/views.py
from django.shortcuts import render
from pprint import pprint
from django.views.generic import FormView,ListView, TemplateView
from django.conf import settings
from supervisor.forms import CategoryForm, SupervisorForm, ItemForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from allauth.account.utils import get_user_model
from core.models import Category, Item, Supervisor,File
from django.shortcuts import redirect,reverse
from django.http import JsonResponse, HttpResponseNotAllowed
from core.utils import has_related_supervisor
from supervisor.mixins import SupervisorMixin

from django.core.files.storage import FileSystemStorage

from ecommerce import settings
# Create your views here.
User = get_user_model()

def dashboard(request):
    return render(request,'supervisor/charts.html')

class ItemList(SupervisorMixin,ListView):
    template_name= "supervisor/tables.html"
    model = Item
    context_object_name = "items"

class CreateItemView(FormView):
    def get(self,*args, **kwargs):
        context = {
            'form' : ItemForm()
        }
        return render(self.request,'supervisor/management/add-item.html',context)
    def post(self, *args, **kwargs):
        form = ItemForm(self.request.POST,self.request.FILES)
        files = self.request.FILES.getlist('image')
        if form.is_valid():
            title = form.cleaned_data['title']
            label = form.cleaned_data['label']
            price = form.cleaned_data['price']
            discount_price = form.cleaned_data['discount_price']
            category = form.cleaned_data['category']
            description = form.cleaned_data['description']
            quantity = form.cleaned_data['quantity']
            for f in files:
                ext = f.name.split(".")[-1].lower()
                if not ext in settings.ACCEPTED_FILES:
                    messages.warning(self.request
                    ,f'This file format is not supported! Please upload {settings.ACCEPTED_FILES} formats')
                    return redirect('supervisor:add-item')
            item = Item(
                title=title,
                label=label,
                price=price,
                discount_price=discount_price,
                category=category,
                description=description,
                quantity=quantity
            )
            item.save()
            if item:
                for f in files:
                    image = File(item= item,file = f)
                    image.save()
                messages.success(self.request,'Item added!')
                return redirect('supervisor:add-item')
            else:
                messages.info(self.request,'Error occured, try again !')
                return redirect('supervisor:add-item')
        else:
            messages.info(self.request,'Form is not valid, try again !')
            return redirect('supervisor:add-item')            
class CategoryListView(SupervisorMixin,ListView):
    def get(self, *args, **kwargs):
        form = CategoryForm()
        categories = Category.objects.all()
        context = {
            "categories" : categories,
            "category_form" : form
        }
        return render(self.request,'supervisor/categories.html',context=context)
    def post(self,*args, **kwargs):
        form = CategoryForm(self.request.POST) or None
        if form.is_valid():
            category = Category(name = form.cleaned_data["category_name"])
            category.save()
            return redirect('supervisor:categories')

        return redirect(self.request,'supervisor:categories')
class CreateSupervisorView(SupervisorMixin,FormView):
    template_name= "add-supervisor.html"
    form_class = SupervisorForm
    def form_valid(self, form):
        try:
            user = User.objects.get(email=form.cleaned_data['email'])
            is_admin = form.cleaned_data['supervisor_type']
            supervisor = Supervisor(
                user = user,
                is_admin = is_admin
            )
#            supervisor.save()
            pprint(supervisor)
            messages.success(self.request,'Supervisor added!')
            return redirect('supervisor:dashboard')

        except ObjectDoesNotExist:
            messages.warning(self.request,'Email does not exist')
            return redirect('supervisor:add-supervisor')
        
def add_category(request):
    try:
        name = request.POST
        pprint(request)
        messages.success(request,'Cateory added!')
        return reverse('core:item-list')
        new_category = Category(
            name = name
        )
        new_category.save()
    except ObjectDoesNotExist:
        messages.warning(request,'The form is invalid!')
        return reverse('core:item-list')


def get_email(request):
    supervisor_required(request.user)
    email = request.GET['email']
    responseUsers = User.objects.filter(email__startswith=email)[:5]
    responseEmails = []
    for responseUser in responseUsers:
        responseEmails.append(responseUser.email)
    pprint(responseEmails)
    return JsonResponse({
        'emails':responseEmails
    })

def supervisor_required(user):
    if has_related_supervisor(user):
        if user.supervisor.is_admin:
            return True
        return HttpResponseNotAllowed("Not allowed")
    else:
        return HttpResponseNotAllowed("Not allowed")

templates/supervisor/add-admin-scripts.html
{% load static %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>


    <script src="{% static 'js/FilePond/FilePond-Plugin-File-Encode.min.js' %}"></script>
    <script src="{% static 'js/FilePond/FilePond-Plugin-File-Validate-Size.min.js' %}"></script>
    <script src="{% static 'js/FilePond/FilePond-Plugin-Image-Exif-Orientation.min.js' %}"></script>
    <script src="{% static 'js/FilePond/FilePond-Plugin-Image-Preview.min.js' %}"></script>
    <script src="{% static 'js/FilePond/FilePond-Plugin-File-Validate-Type.min.js' %}"></script>
    <script src="{% static 'js/FilePond/FilePond-Plugin-Image-Crop.min.js' %}"></script>
    <script src="{% static 'js/FilePond/FilePond-Plugin-Image-Resize.min.js' %}"></script>
    <script src="{% static 'js/FilePond/FilePond-Plugin-Image-Transform.min.js' %}"></script>
    <script src="{% static 'js/FilePond/FilePond-Plugin-Pdf-Preview.min.js' %}"></script>
    <script src="{% static 'js/FilePond/FilePond.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/utils/email-selector.js' %}"></script>

templates/supervisor/admin-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>
<body>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
  {% endif %}
    {% block content %}
    
    {% endblock content %}
    {% include 'supervisor/admin-scripts.html' %}
</body>
</html>

templates/supervisor/admin-scripts.html
{% load static %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
    

templates/supervisor/categories.html
{% extends 'supervisor/tables-base.html' %}
{% load static %}
{% block content %}


    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'supervisor/sidebar.html' %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                {% include 'supervisor/topbar.html' %}
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
                    <nav class="mb-4 navbar navbar-expand-lg navbar-light bg-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                          <div class="navbar-nav">
                            <a class="nav-item nav-link" href="{% url 'supervisor:tables' %}">Items <span class="sr-only">(current)</span></a>
                            <a class="nav-item nav-link active" href="{% url 'supervisor:categories' %}">Categories</a>

                          </div>
                        </div>
                      </nav>

                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary d-inline">Categories Table</h6>
                            <a class="btn btn-primary float-right" data-toggle="modal" href="#add-category">Add Category <i class="fas fa-plus"></i></a>
                        </div>
                        {% include 'modals/add-category.html' %}
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Items Count</th>
                                            <th>Sold</th>
                                            <th>Start date</th>
                                            <th>Total amount</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Name</th>
                                            <th>Items Count</th>
                                            <th>Sold</th>
                                            <th>Start date</th>
                                            <th>Total amount</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for category in categories %}
                                        <tr>
                                            <td>{{ category.name }}</td>
                                            <td>{{ category.get_items_count }}</td>
                                            <td>{{ category.get_sold_items }}</td>
                                            <td>{{ category.start_date }}</td>
                                            <td>50000</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    {% include 'supervisor/tables-scripts.html' %}
    {% endblock content %}
    

templates/supervisor/charts.html
{% extends 'supervisor/tables-base.html' %}
{% block content %}
<!-- Page Wrapper -->
<div id="wrapper">

        <!-- Sidebar -->
        {% include 'supervisor/sidebar.html' %}
        <!-- End of Sidebar -->
        
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                
                <!-- Topbar -->
                {% include 'supervisor/topbar.html' %}
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Charts</h1>
                    <p class="mb-4">Chart.js is a third party plugin that is used to generate the charts in this theme.
                        The charts below have been customized - for further customization options, please visit the <a
                            target="_blank" href="https://www.chartjs.org/docs/latest/">official Chart.js
                            documentation</a>.</p>

                    <!-- Content Row -->
                    <div class="row">

                        <div class="col-xl-8 col-lg-7">

                            <!-- Area Chart -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
                                </div>
                                <div class="card-body">
                                    <div class="chart-area">
                                        <canvas id="myAreaChart"></canvas>
                                    </div>
                                    <hr>
                                    Styling for the area chart can be found in the
                                    <code>/js/demo/chart-area-demo.js</code> file.
                                </div>
                            </div>

                            <!-- Bar Chart -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
                                </div>
                                <div class="card-body">
                                    <div class="chart-bar">
                                        <canvas id="myBarChart"></canvas>
                                    </div>
                                    <hr>
                                    Styling for the bar chart can be found in the
                                    <code>/js/demo/chart-bar-demo.js</code> file.
                                </div>
                            </div>

                        </div>

                        <!-- Donut Chart -->
                        <div class="col-xl-4 col-lg-5">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
                                </div>
                                <!-- Card Body -->
                                <div class="card-body">
                                    <div class="chart-pie pt-4">
                                        <canvas id="myPieChart"></canvas>
                                    </div>
                                    <hr>
                                    Styling for the donut chart can be found in the
                                    <code>/js/demo/chart-pie-demo.js</code> file.
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    {% include 'supervisor/charts-script.html' %}
    {% endblock content %}

templates/supervisor/tables.html
{% extends 'supervisor/tables-base.html' %}
{% load static %}
{% block content %}


    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% include 'supervisor/sidebar.html' %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                {% include 'supervisor/topbar.html' %}
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
                    <nav class="mb-4 navbar navbar-expand-lg navbar-light bg-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                          <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                          <div class="navbar-nav">
                            <a class="nav-item nav-link active" href="{% url 'supervisor:tables' %}">Items <span class="sr-only">(current)</span></a>
                            <a class="nav-item nav-link" href="{% url 'supervisor:categories' %}">Categories</a>

                          </div>
                        </div>
                      </nav>

                    <!-- DataTales Example -->

                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary d-inline">Items Table</h6>
                            <button class="btn btn-primary float-right" data-toggle="modal" data-target=".bd-example-modal-lg">Add Item</button>
                            {% include 'modals/add-item.html' %}
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Category</th>
                                            <th>Sold</th>
                                            <th>Left</th>
                                            <th>Start date</th>
                                            <th>Total amount</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Name</th>
                                            <th>Category</th>
                                            <th>Sold</th>
                                            <th>Left</th>
                                            <th>Start date</th>
                                            <th>Total amount</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        {% for item in items %}
                                        <tr>
                                            <td>{{ item.title }}</td>
                                            <td>{{ item.category.name }}</td>
                                            <td>{{ item.sold }}</td>
                                            <td>{{ item.quantity }}</td>
                                            <td>{{ item.start_date }}</td>
                                            <td>{{ item.price }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    {% include 'supervisor/tables-scripts.html' %}
    {% endblock content %}
    