core/urls.py
from unicodedata import name
from django.urls import path, include


from .views import  CheckoutView, ItemDetailView, ItemList, add_coupon,add_to_cart, OrderSummaryView, remove_from_cart,remove_single_item_from_cart
from django.shortcuts import render
app_name = "core"
urlpatterns = [
    path('',ItemList.as_view(),name='item-list'),
#    path('checkout/',lambda request: render(request,'checkout-page.html'),name='checkout'),
    path('product/add-to-cart/<slug>/', add_to_cart,name='add-to-cart'),
    path('product/remove-from-cart/<slug>/', remove_from_cart,name='remove-from-cart'),
    path('product/<slug>/', ItemDetailView.as_view(),name='item-detail'),
    path('order-summary/', OrderSummaryView.as_view(),name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
     name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('add-coupon/',add_coupon , name="add-coupon")

]
"""     path('payment/',CreatePayment.as_view(), name="payment"),
    path('payment-confirm/',PaymentConfirmation.as_view(), name="payment-confirmation"),
    path("payment-status/<int:pk>/",PaymentStatus.as_view(),name="payment-status"), """

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls',namespace='core')),
    path('supervisor/',include('supervisor.urls',namespace='supervisor')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

supervisor/urls.py
from django.urls import path, include

from supervisor.views import CreateSupervisorView, ItemList, add_category, CreateItemView, dashboard, get_email,CategoryListView

app_name='supervisor'

urlpatterns = [
    path('',dashboard,name='dashboard'),
    path('add-supervisor/',CreateSupervisorView.as_view(),name='add-supervisor'),
    path('add-category/',add_category,name='add-category'),
    path('get-email/',get_email,name='get-email'),
    path('tables/',ItemList.as_view(),name='tables'),
    path('add-item/',CreateItemView.as_view(),name='add-item'),
    path('tables/categories/',CategoryListView.as_view(),name='categories'),
]

core/models.py
from email.policy import default
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from chargily_epay_django.models import AnonymPayment,FakePaymentMixin
from django.utils.text import slugify 
from django.utils.crypto import get_random_string


from autoslug import AutoSlugField

from core.constants import LABEL_CHOICES, DELIVERY_MODE, PAYMENT_CANCELED, PAYMENT_EXPIRED, PAYMENT_FAILED, PAYMENT_IN_PROGRESS, PAYMENT_PAID, WILAYA
from core.forms import PAYMENT_MODE


# Create your models here.


ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

class Address(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    zip = models.CharField(max_length=20)
    wilaya = models.CharField(choices = WILAYA, max_length=100)    
    apartment = models.CharField(max_length=200)    
    address1 = models.CharField(max_length=200)    
    address2 = models.CharField(max_length=200,null=True,blank=True)
    def __str__(self):
        return f"{self.id}- {self.user.username} address: {self.address1}"    

class Category(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateTimeField(auto_now_add=True)
    def get_items_count(self):
        count = Item.objects.filter(category=self).count()
        return count
    def get_sold_items(self):
        items = Item.objects.filter(category=self)
        sold = 0
        for item in items:
            sold += item.sold
        return sold
    def __str__(self):
        return self.name
class Item(models.Model):
    title = models.CharField(max_length=100)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1 , default='P')
    price = models.FloatField()
    discount_price = models.FloatField(blank=True , null=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    start_date = models.DateTimeField(auto_now_add=True)
    slug = AutoSlugField(populate_from='title',unique=True)
    description = models.TextField()
    quantity = models.IntegerField(default = -1)
    sold = models.IntegerField(default = 0)
    total_amount = models.IntegerField(default = 0)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("core:item-detail", kwargs={"slug": self.slug})
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={"slug": self.slug})
    def save(self, *args, **kwargs):
        random_string = get_random_string(8,'0123456789')
        self.slug = slugify(f"{self.pk,self.title}")
        super(Item, self).save(*args, **kwargs)
    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={"slug": self.slug})
    
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, blank=True, null=True)
    item = models.ForeignKey(Item , on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    ordered = models.BooleanField(default=False)
    order_confirmed = models.BooleanField(default=False)
    quantity = models.IntegerField(default = 1)
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    def get_total_item_price(self):
        return self.item.price * self.quantity
    def get_total_item_price_discount(self):
        return self.item.discount_price * self.quantity
        
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_item_price_discount()
        
    def get_item_total(self):
        if(self.item.discount_price):
            return self.get_total_item_price_discount()
        else:
            return self.get_total_item_price()
class Coupon(models.Model):
    code = models.CharField(max_length=15,unique=True)
    used = models.BooleanField(default=False)
    discount = models.IntegerField()
    def __str__(self):
        return f"{self.code} used: {'used' if self.used else 'not yet'}"

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default = False)
    coupon = models.ForeignKey(Coupon,blank=True,null=True,on_delete=models.DO_NOTHING)
    def __str__(self):
        return self.user.username
    def get_total_price(self):
        total = 0
        for item in self.items.all():
            total += item.get_item_total()
        return total

PAYMENT_STATUS = {
    (PAYMENT_EXPIRED, "EXPIRED"),
    (PAYMENT_IN_PROGRESS, "IN PROGRESS"),
    (PAYMENT_PAID, "PAID"),
    (PAYMENT_FAILED, "FAILED"),
    (PAYMENT_CANCELED, "CANCELED"),
}

class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.DO_NOTHING)
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.IntegerField()
    payment_mode = models.CharField(choices=PAYMENT_MODE, max_length = 100)
    delivery_mode = models.CharField(choices=DELIVERY_MODE, max_length = 100)
    invoice = models.CharField(max_length=20,unique=True)
    status = models.CharField(
        max_length=25, default=PAYMENT_IN_PROGRESS, choices=PAYMENT_STATUS
    )
    def __str__(self):
        return f"{self.invoice} total: {self.order.get_total_price()}"

class Supervisor(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.user.first_name} {self.user.first_name}"

class File(models.Model):
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    file = models.FileField(upload_to=f'images/%Y/%m/%d')

templates/add-supervisor.html
{% extends 'supervisor/tables-base.html' %}
{% load static %}
{% block content %}
<!-- Page Wrapper -->
<div id="wrapper">
  
  <!-- Sidebar -->
  {% include 'supervisor/sidebar.html' %}
  <!-- End of Sidebar -->
  
  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">
    
    <!-- Main Content -->
    <div id="content">
      
      <!-- Topbar -->
      {% include 'supervisor/topbar.html' %}
      <!-- End of Topbar -->
      
      <!-- Begin Page Content -->
      
      
      <!-- /.container-fluid -->
      <div class="container mt-5">
              <div class="row justify-content-center">
              <div class="col-8">
                  <div class="h1 text-center mb-5">Add Supervisor</div>            
                  <form method="POST">
                      {% csrf_token %}
                      <!-- 2 column grid layout with text inputs for the first and last names -->
                      
                      <!-- Email input -->
                      <div class="form-outline mb-4">
                          <label class="form-label" for="form3Example3">Email address</label>
                          {{ form.email }}
                          <div id="email-selector" class="list-group display-inline" style="display: none;">
                          </div>
                      </div>
      
                      <!-- Checkbox -->
                      <div class="form-outline mb-4">
                          <label class="form-check-label" for="form2Example33">
                            Supervisor type
                          </label>
                          {{ form.supervisor_type}}
                      </div>
                    
                      <!-- Checkbox -->
                      <div class="form-outline mb-4">
                          <label class="form-check-label" for="form2Example33">
                            Supervisor type
                          </label>
                      </div>
                    
                      <!-- Submit button -->
                      <button type="submit" class="btn btn-primary btn-block mb-4">Add supervisor</button>
                    </form>
              </div>
          </div>
      </div>

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    {% include 'supervisor/add-admin-scripts.html' %}
    <script src="https://unpkg.com/filepond@^4/dist/filepond.js"></script>
    {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/navbarDropdown.css' %}" rel="stylesheet">
  <!-- Latest compiled and minified CSS -->
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>


<body>
  {% include 'navbar.html' %}
  {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
      {% endif %}
    {% block body %}
    
    
    <div style="min-height: 65vh;">
      {% block content %}
      {% endblock content %}
    </div>
    {% include 'scripts.html' %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
    {% include 'footer.html' %}

</body>
</html>

{% comment %}       <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul> {% endcomment %}

templates/checkout-page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
              {% csrf_token %}
              {{ form|crispy }}

              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
              
            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
            {% csrf_token %}
            <div class="input-group">
              <input id="code" name="code" type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->



  {% endblock content %}
          {% comment %}               <!--Grid row-->
                        <div class="row">
          
                          <!--Grid column-->
                          <div class="col-md-6 mb-2">
          
                            <!--firstName-->
                            <div class="md-form ">
                              <input type="text" id="firstName" class="form-control">
                              <label for="firstName" class="">First name</label>
                            </div>
          
                          </div>
                          <!--Grid column-->
          
                          <!--Grid column-->
                          <div class="col-md-6 mb-2">
          
                            <!--lastName-->
                            <div class="md-form">
                              <input type="text" id="lastName" class="form-control">
                              <label for="lastName" class="">Last name</label>
                            </div>
          
                          </div>
                          <!--Grid column-->
          
                        </div>
                        <!--Grid row-->
          
                        <!--Username-->
                        <div class="md-form input-group pl-0 mb-5">
                          <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">@</span>
                          </div>
                          <input type="text" class="form-control py-0" placeholder="Username" aria-describedby="basic-addon1">
                        </div>
          
                        <!--email-->
                        <div class="md-form mb-5">
                          <input type="text" id="email" class="form-control" placeholder="youremail@example.com">
                          <label for="email" class="">Email (optional)</label>
                        </div>
          
                        <!--address-->
                        <div class="md-form mb-5">
                          <input type="text" id="address" class="form-control" placeholder="1234 Main St">
                          <label for="address" class="">Address</label>
                        </div>
          
                        <!--address-2-->
                        <div class="md-form mb-5">
                          <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite">
                          <label for="address-2" class="">Address 2 (optional)</label>
                        </div>
          
                        <!--Grid row-->
                        <div class="row">
          
                          <!--Grid column-->
                          <div class="col-lg-4 col-md-12 mb-4">
          
                            <label for="country">Country</label>
                            <select class="custom-select d-block w-100" id="country" required>
                              <option value="">Choose...</option>
                              <option>United States</option>
                            </select>
                            <div class="invalid-feedback">
                              Please select a valid country.
                            </div>
          
                          </div>
                          <!--Grid column-->
          
                          <!--Grid column-->
                          <div class="col-lg-4 col-md-6 mb-4">
          
                            <label for="state">State</label>
                            <select class="custom-select d-block w-100" id="state" required>
                              <option value="">Choose...</option>
                              <option>California</option>
                            </select>
                            <div class="invalid-feedback">
                              Please provide a valid state.
                            </div>
          
                          </div>
                          <!--Grid column-->
          
                          <!--Grid column-->
                          <div class="col-lg-4 col-md-6 mb-4">
          
                            <label for="zip">Zip</label>
                            <input type="text" class="form-control" id="zip" placeholder="" required>
                            <div class="invalid-feedback">
                              Zip code required.
                            </div>
          
                          </div>
                          <!--Grid column-->
          
                        </div>
                        <!--Grid row-->
          
                        <hr>
          
                        <div class="custom-control custom-checkbox">
                          <input type="checkbox" class="custom-control-input" id="same-address">
                          <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
                        </div>
                        <div class="custom-control custom-checkbox">
                          <input type="checkbox" class="custom-control-input" id="save-info">
                          <label class="custom-control-label" for="save-info">Save this information for next time</label>
                        </div>
          
                        <hr>
          
                        <div class="d-block my-3">
                          <div class="custom-control custom-radio">
                            <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
                            <label class="custom-control-label" for="credit">Credit card</label>
                          </div>
                          <div class="custom-control custom-radio">
                            <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                            <label class="custom-control-label" for="debit">Debit card</label>
                          </div>
                          <div class="custom-control custom-radio">
                            <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                            <label class="custom-control-label" for="paypal">Paypal</label>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-6 mb-3">
                            <label for="cc-name">Name on card</label>
                            <input type="text" class="form-control" id="cc-name" placeholder="" required>
                            <small class="text-muted">Full name as displayed on card</small>
                            <div class="invalid-feedback">
                              Name on card is required
                            </div>
                          </div>
                          <div class="col-md-6 mb-3">
                            <label for="cc-number">Credit card number</label>
                            <input type="text" class="form-control" id="cc-number" placeholder="" required>
                            <div class="invalid-feedback">
                              Credit card number is required
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-3 mb-3">
                            <label for="cc-expiration">Expiration</label>
                            <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
                            <div class="invalid-feedback">
                              Expiration date required
                            </div>
                          </div>
                          <div class="col-md-3 mb-3">
                            <label for="cc-expiration">CVV</label>
                            <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
                            <div class="invalid-feedback">
                              Security code required
                            </div>
                          </div>
                        </div>
                        <hr class="mb-4"> {% endcomment %}

templates/navbar.html
{% load cart_template_tags %}

<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light white scrolling-navbar sticky-top">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">Ecommerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              {% if request.path == path %}
              <span class="sr-only">(current)</span>
              {% endif %}
            </a>
          </li>
          {% if is_supervisor %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'supervisor:dashboard' %}">Dashboard</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:checkout' %}"
              target="_blank">Products</a>
          </li>
          <!-- 
              <li class="nav-item">
                <a class="nav-link waves-effect" href="https://mdbootstrap.com/education/bootstrap/" target="_blank">Free
                  tutorials</a>
              </li>
          -->
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:order-summary' %}">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="https://github.com/mdbootstrap/bootstrap-material-design" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              <i class="fab fa-github mr-2"></i>MDB GitHub
            </a>
          </li>
        </ul>

      </div>

    </div>
  </nav>

  <!-- Navbar -->

templates/order-summary.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <!--Main layout-->
<main>
  <div class="container">
<div class="h1 mt-2">
  Order Summary
</div>
 
 <!--Table-->
<table class="table table-hover table-fixed">

    <!--Table head-->
    <thead>
      <tr>
        <th>#</th>
        <th>Item title</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total Item Price</th>
      </tr>
    </thead>
    <!--Table head-->
  
    <!--Table body-->
    <tbody>
      {% for item in order.items.all %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item.item.title }}</td>
        <td>{{ item.item.price }}</td>
        <td>
          
          <a href="{% url 'core:add-to-cart' item.item.slug %}"><i class="fas fa-plus mr-1"></i></a> 
          {{ item.quantity }}
          <a href="{% url 'core:remove-single-item-from-cart' item.item.slug %}"><i class="fas fa-minus ml-1"></i></a> 
        </td>
        <td>
        {% if item.item.discount_price %}
        {{ item.get_total_item_price_discount }} <span class="ml-1 badge badge-primary">
          amount saved: {{ item.get_amount_saved }}</span>
        {% else %}
        {{ item.get_total_item_price }}
        {% endif %}
        <a style='color: red;' href="{% url 'core:remove-from-cart' item.item.slug %}">
          <i class="fas fa-trash float-right"></i>
      </a>
      </td>
      </tr>
      {% empty %}
      <tr>
          <td colspan='5'>Your cart is empty</td>
      </tr>
      {% endfor %}
      {% if order.get_total_price %}
      <tr>
        <td colspan="4"><b>Order Total</b></td>
        <td><b>{{ order.get_total_price }}</b></td>
      </tr>
      {% endif %}
      
    </tbody>
    <!--Table body-->
    
  </table>
  
  {% if order.get_total_price %}
    <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
  {% endif %}
  <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
  <!--Table-->

</div>
</main>

{% endblock content %}